---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: boolFlag

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: isLoggedIn
          operator: is-true
    flagValue: false
