---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: Customer migration feature

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: false

conditions:
  - allOf:
      - property:
          name: isBetaUser
          operator: is-true
    flagValue: true
  - allOf:
      - anyOf:
          - group:
              name: Logged in Cloudbees
    flagValue: true
