---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: boolFlag

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - flag:
          name: Customer migration feature
          value: "false"
    flagValue: false
