---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: newString

enabled: false

stickinessProperty: rox.distinct_id

defaultValue: '!;lm;lfasdfasdfasdf'

conditions: []
