---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: default.show

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions: []
